site_name: Admin CRM

nav:
  - Mise en production :
      - Installation : mise-en-production/installation.md
      - Migration Magento > CRM : mise-en-production/migration.md

theme:
  name: readthedocs
  locale: fr

markdown_extensions:
  # Admonition : boxes of different types : attention, caution, danger, error, hint, important, note, tip, and warning; see : https://python-markdown.github.io/extensions/admonition/
  - admonition
  # Attribute Lists : add attributes to HTML elements (like image sizes) https://python-markdown.github.io/extensions/definition_lists/
  - attr_list
  # Definition Lists : create a glossary https://python-markdown.github.io/extensions/definition_lists/
  - def_list
